### ISSUE TITLE
Can testing on Travis CI Windows be part of the acceptance criteria for Chocolatey packages?

### ISSUE THREAD

**Issue by cclauss** [chocolatey/package-verifier#72]
Can testing on [Travis CI Windows](https://docs.travis-ci.com/user/reference/windows/) be part of the acceptance criteria for Chocolatey packages?  A quick Travis CI test on a Chocolatey package could be kicked off via a __.travis.yml__ file like:
```yaml
# https://docs.travis-ci.com/user/reference/windows/
os: windows
language: bash  # "language: java" is not yet supported on Travis CI Windows
install: choco install xyz
script: xyz --version  # or some other simple test
```

**Comment by cclauss** [comment]
For automated testing of installers in their own repos:
```yaml
# https://docs.travis-ci.com/user/reference/windows/
os: windows
language: c
env: 
  - PACKAGE=abc   BIN_DIR="/c/Program Files/abc/bin"
  - PACKAGE=xyz   BIN_DER="/c/Program Files/xyz/bin"
install: 
  - cd packages/$PACKAGE
  - choco pack
  - pwd ; ls -l
  - choco install $PACKAGE -dv --force -s .
  - export PATH="$BIN_DER:$PATH"
script:
  - $PACKAGE -version
  - choco uninstall $PACKAGE
```
